---
- hosts: tag_AnsibleGroup_bastions
  gather_facts: true
  become: true
  tasks:
  - name: Install required packages 
    yum: 
     name: "{{item}}"
     state: latest 
    loop: 
      - python 
      - python-pip 
      - python-devel 
      - gcc
  - name: Install tower-cli
    pip:
     name: ansible-tower-cli
     state: latest
  - name: List key files
    shell: (cd /root/.ssh; find . -maxdepth 1 -type f -iname '*key.pem')| cut -d'/' -f2
    register: file_to_copy

