---
- hosts: tag_AnsibleGroup_bastions
  gather_facts: true
  become: true

  tasks:

  - name: Install required packages 
    yum: 
     name: "{{item}}"
     state: latest 
    loop: 
      - python 
      - python-pip 
      - python-devel 
      - gcc

  - name: Install tower-cli
    pip:
     name: ansible-tower-cli
     state: latest

  - name: List key files
    shell: (cd /root/.ssh; find . -maxdepth 1 -type f -iname '*key.pem')| cut -d'/' -f2
    register: file_to_copy

  - name: Tower Credentials key file
    tower_credential:
      name: Credentials for AWS instances
      organization: Default
      state: present
      kind: ssh
      tower_host: tower1.28dc.example.opentlc.com
      tower_username: admin
      tower_password: r3dh4t1!
      ssh_key_data: "/root/.ssh/{{ file_to_copy.stdout }}"
      username: ec2-user

  - name: Associate AWS tags as children to apps group
    shell: |
      tower-cli config host tower1.28dc.example.opentlc.com
      tower-cli config username admin
      tower-cli config password r3dh4t1!
      tower-cli group associate --group tag_AnsibleGroup_apps --parent apps --inventory "AWS inventory"
