- hosts: jumpbox
  tasks:

  - name: Delete frontend instance
    include_role:
       name: osp-del-instances
       vars_from: frontend.yaml

  - name: Delete app1 instance
    include_role:
       name: osp-del-instances
       vars_from: app1.yaml

  - name: Delete app2 instance
    include_role:
       name: osp-del-instances
       vars_from: app2.yaml

  - name: Delete db instance
    include_role:
       name: osp-del-instances
       vars_from: db.yaml
