---

- name: Run repos roles
  hosts: tag_AnsibleGroup_frontends:tag_AnsibleGroup_apps:tag_AnsibleGroup_appdbs
  become: yes
  gather_facts: false
  roles:
    - { name: repos }

- name: Run haproxy role
  hosts: tag_AnsibleGroup_frontends
  become: yes
  gather_facts: false
  roles:
    - { name: haproxy }

- name: Run tomcat role
  hosts: tag_AnsibleGroup_apps
  become: yes
  gather_facts: false
  roles:
    - { name: tomcat }

- name: Run postgres role
  hosts: tag_AnsibleGroup_appdbs
  become: yes
  gather_facts: false
  roles:
    - { name: postgres }

