---

- name: Provision AWS
  hosts: bastion
  become: true
  gather_facts: false
  vars:
    scriptdir: /root/aws
    bindir: "{{ scriptdir }}/bin"
    baseurl: http://www.opentlc.com/download/ansible_bootcamp/scripts

  tasks:
  - name: Create directory
    file:
      path: "{{ bindir }}"
      state: directory
      mode: 0755

  - name: Get scripts
    get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
      mode: 0755
    with_items:
      - { url: "{{ baseurl }}/common.sh",    dest: "{{ scriptdir }}" }
      - { url: "{{ baseurl }}/order_svc.sh", dest: "{{ scriptdir }}" }
      - { url: "{{ baseurl }}/jq-linux64",   dest: "{{ bindir }}/jq" }

  - name: Run provision script
    shell: |
      export PATH={{ scriptdir }}:{{ bindir }}:$PATH
      export username={{ my_user }}
      export password={{ my_password }}
      export uri={{ my_uri }}
      ./order_svc.sh -y -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1
    args:
      executable: /bin/bash
      chdir: "{{ scriptdir }}"

  - name: Pause 15 minutes while AWS builds
    shell: |
      sleep 900
