---

- name: SMOKE TEST
  hosts: jumpbox
  roles:
  - osp-facts
  gather_facts: true
  become: true

- name: Run smoketest
  hosts: frontends
  become: yes
  gather_facts: false

  tasks:
  - name: Connect to frontend URI
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: output

  - debug: var=output

  - name: Fail if output not correct
    fail:
    when: "'Ansible has done its job' not in output"
